matrix:
  include:
    - os: linux
    - os: osx

language: node_js
node_js:
  - "node"
  - "8"

cache:
  directories:
    - "node_modules"
services:
  - mysql

script:
  - npm run lintNoFix
  - npm run test

before_install:
  - mysql -e 'CREATE USER 'xud'@'localhost'';
  - mysql -e 'GRANT ALL PRIVILEGES ON `xud\_%`.* TO `xud`@`%`;'
